### ISSUE TITLE
IRV Election not working properly

### ISSUE THREAD

**Issue by ruippgoncalves** [kevmoo/vote.dart#23]
I was using this library when I found this:

    final election = IrvElection([
        RankedBallot(['b', 'c', 'a'])
    ]);

This returns the error
Error: Assertation Failed:
sorted(candidates)
is not true

-------------------------------------

I traced the problem in debugger and util.dart line 13

    if (last != null && last.compareTo(item) > 0) {

is trying to compare "c" to "a"

Am I using this election wrong?

**Comment by kevmoo** [comment]
Ha! I'm so glad someone is using this! I'll take a look....

**Comment by kevmoo** [comment]
I just published v1 which has a lot of fixes. Try that and let me know!

**Comment by ruippgoncalves** [comment]
It did not solved. I will give you the entire log it returns:

════════════════════════════════════════════════════════════════════════════════════════════════════
Error: Assertion failed: file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/vote-1.0.0/lib/src/election_place.dart:15:16
sorted(candidates)
is not true
    at Object.throw_ [as throw] (http://localhost:8080/dart_sdk.js:5334:11)
    at Object.assertFailed (http://localhost:8080/dart_sdk.js:5270:15)
    at new ElectionPlace.new (http://localhost:8080/packages/vote/src/election_place.dart.lib.js:51:53)
    at Function.new (http://localhost:8080/packages/vote/src/irv_election.dart.lib.js:93:24)
    at http://localhost:8080/packages/client/management/data/data.dart.lib.js:1101:62
    at data._DataState.new.setState (http://localhost:8080/packages/flutter/src/widgets/widget_span.dart.lib.js:16616:22)
    at http://localhost:8080/packages/client/management/data/data.dart.lib.js:1068:18
    at _RootZone.runUnary (http://localhost:8080/dart_sdk.js:38889:58)
    at _FutureListener.then.handleValue (http://localhost:8080/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:8080/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:8080/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:8080/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:8080/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:8080/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:8080/dart_sdk.js:39182:13)
    at http://localhost:8080/dart_sdk.js:34689:9

------------------------------------------------------------------------------------------------------------------------------------
I tried using dart and it works, only when running in flutter (at least web and android) it's when the error occurred. I've made here a reproducible app with error
------------------------------------------------------------------------------------------------------------------------------------

```
import 'package:flutter/material.dart';
import 'package:vote/vote.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var voteDt = IrvElection([
    RankedBallot(['b', 'c', 'a'])
  ]);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Winner is',
            ),
            Text(
              '${voteDt.hasSingleWinner ? voteDt.singleWinner : 'Tie'}',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by ruippgoncalves** [comment]
I solved the problem. It is in the pull requests...
